version: 2.1

setup: true

parameters:
  manual-workflow-name:
    type: string
    default: ""

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  setup:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Build pipeline parameters
          command: |
            echo "{\"manual-workflow-name\": \"${MANUAL_WORKFLOW_NAME:-}\"}" \
              > /tmp/pipeline-params.json
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          parameters: /tmp/pipeline-params.json

workflows:
  initial-setup:
    jobs:
      - setup